"use client";
import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { Check, CircleAlert, ExternalLink, LoaderCircle, RefreshCw } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { SolanaProofButton } from "@/components/solana-proof-button";
import { flags as initial } from "@/lib/demo-data";
type Flag = (typeof initial)[number];
export default function Page() {
  const [flags, setFlags] = useState(initial); const [scan, setScan] = useState("Run scheduled scan now"); const [resolving, setResolving] = useState(""); const [receipt, setReceipt] = useState<{ label: string; explorer: string } | null>(null);
  async function run() { setScan("Scanning leases..."); const response = await fetch("/api/compliance/scan", { method: "POST" }); const data = await response.json(); setScan(`${data.flags.length} unique open signals · idempotent ${data.idempotent ? "verified" : "failed"}`); }
  async function resolve(flag: Flag, index: number) { setResolving(flag.subject); const response = await fetch("/api/solana/proof", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ event: `resolve-compliance-${index + 1}` }) }); const data = await response.json(); if (response.ok && data.verified) { setReceipt({ label: flag.subject, explorer: data.explorer }); setFlags((current) => current.filter((item) => item.subject !== flag.subject)); } setResolving(""); }
  return <AppShell eyebrow="Compliance radar" title="Lease conditions surfaced while actionable" description="A flag leaves the queue only after its resolution receipt confirms on Solana devnet."><section className="toolbar"><button className="secondaryButton" onClick={run}><RefreshCw />{scan}</button><SolanaProofButton event="compliance-scan-attested" /></section>{receipt && <a className="resolutionReceipt" href={receipt.explorer} target="_blank" rel="noreferrer"><Check />Resolved {receipt.label}<ExternalLink /></a>}<section className="flagGrid"><AnimatePresence>{flags.map((flag, index) => <motion.article layout exit={{ opacity: 0, scale: .95, height: 0 }} transition={{ duration: .3 }} className={`flagCard ${flag.severity}`} key={flag.subject}><div><CircleAlert /><span>{flag.severity}</span></div><p>{flag.type}</p><h2>{flag.subject}</h2><small>{flag.detail}</small><button onClick={() => resolve(flag, index)} disabled={resolving === flag.subject}>{resolving === flag.subject ? <LoaderCircle className="spin" /> : <Check />}{resolving === flag.subject ? "Confirming receipt..." : "Resolve with proof"}</button></motion.article>)}</AnimatePresence></section></AppShell>;
}