"use client";
import { useState } from "react";
import { Connection, PublicKey, SystemProgram, Transaction } from "@solana/web3.js";
import { Check, CreditCard, ExternalLink, LoaderCircle, Wallet } from "lucide-react";
import { AppShell } from "@/components/app-shell";
declare global { interface Window { solana?: { connect: () => Promise<{ publicKey: PublicKey }>; signTransaction: (transaction: Transaction) => Promise<Transaction> } } }
type Receipt = { signature: string; explorer: string; slot: number };
export default function Page() {
  const [receipt, setReceipt] = useState<Receipt | null>(null); const [status, setStatus] = useState("Connect wallet and pay on devnet"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function pay() { try { setLoading(true); setError(""); if (!window.solana?.signTransaction) throw new Error("Install Phantom, Solflare, or another compatible Solana wallet."); setStatus("Connecting wallet..."); const { publicKey } = await window.solana.connect(); const connection = new Connection(process.env.NEXT_PUBLIC_SOLANA_RPC_URL || "https://api.devnet.solana.com", "confirmed"); const signerStatus = await fetch("/api/solana/status").then((response) => response.json()); if (!signerStatus.signer?.publicKey) throw new Error("The DwellNerve devnet operator is unavailable."); const recipient = new PublicKey(signerStatus.signer.publicKey); const latest = await connection.getLatestBlockhash("confirmed"); const transaction = new Transaction({ feePayer: publicKey, recentBlockhash: latest.blockhash }).add(SystemProgram.transfer({ fromPubkey: publicKey, toPubkey: recipient, lamports: 100_000 })); setStatus("Approve 0.0001 SOL devnet transfer..."); const signed = await window.solana.signTransaction(transaction); const signature = await connection.sendRawTransaction(signed.serialize(), { skipPreflight: false }); await connection.confirmTransaction({ signature, blockhash: latest.blockhash, lastValidBlockHeight: latest.lastValidBlockHeight }, "confirmed"); setStatus("Verifying payment on-chain..."); const response = await fetch("/api/payments/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ signature }) }); const verification = await response.json(); if (!response.ok || !verification.verified) throw new Error(verification.error || "Payment could not be verified."); setReceipt(verification); setStatus("Devnet payment verified"); } catch (paymentError) { setError(paymentError instanceof Error ? paymentError.message : "Payment failed."); setStatus("Try devnet payment again"); } finally { setLoading(false); } }
  return <AppShell eyebrow="Tenant payments" title="A ledger you can verify" description="This MVP proves the payment workflow with a real wallet-signed Solana devnet transfer; no real-world rent is charged."><section className="paymentCard"><div><p>August rent obligation</p><h2>Lease ledger</h2><strong>{receipt ? "$0" : "$1,850"}</strong><span>{receipt ? "Devnet settlement proof attached" : "Demo verification amount: 0.0001 SOL on devnet"}</span></div>{receipt ? <div className="paymentSuccess"><Check />Verified at slot {receipt.slot}</div> : <button className="primaryButton" onClick={pay} disabled={loading}>{loading ? <LoaderCircle className="spin" /> : <Wallet />}{status}</button>}{receipt && <a className="receiptLink" href={receipt.explorer} target="_blank" rel="noreferrer">Open transaction <ExternalLink /></a>}{error && <small className="paymentError">{error}</small>}</section><section className="panel"><div className="panelHead"><div><p className="eyebrow">Receipts</p><h2>Payment history</h2></div><span className="networkPill">Solana devnet</span></div>{receipt && <div className="receiptRow liveReceipt"><span>August 2026 proof</span><strong>0.0001 SOL</strong><small>{receipt.signature.slice(0, 12)}... confirmed</small></div>}<div className="receiptRow"><span>July 2026 rent</span><strong>$1,850</strong><small>Paid July 2 · Receipt DN-72911</small></div><div className="receiptRow"><span>June 2026 rent</span><strong>$1,850</strong><small>Paid June 1 · Receipt DN-71804</small></div></section><section className="walletHelp"><CreditCard /><div><strong>Need devnet SOL?</strong><p>Use a devnet-funded wallet. The verifier rejects failed transactions, wrong recipients, and transfers below 0.0001 SOL.</p></div></section></AppShell>;
}