"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Bot, LoaderCircle, Sparkles } from "lucide-react";
type Brief = { headline: string; briefing: string; priorities: { action: string; owner: string; deadline: string; reason: string }[]; watch: string; provider: string; model: string };
export function PortfolioAgent() {
  const [brief, setBrief] = useState<Brief | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function run() { setLoading(true); setError(""); const response = await fetch("/api/agent/portfolio-brief", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ focus: "operations" }) }); const data = await response.json(); if (!response.ok) setError(data.error || "Agent failed."); else setBrief(data); setLoading(false); }
  return <section className="agentPanel"><div className="agentIntro"><span><Bot size={18} /> Live portfolio agent</span><h2>{brief?.headline || "Turn the portfolio readout into the next three actions."}</h2><p>{brief?.briefing || "Groq reads the current repair, collection, and compliance signals. Deterministic safety rules still stay in control of emergency classification."}</p><button className="primaryButton" onClick={run} disabled={loading}>{loading ? <LoaderCircle className="spin" size={17} /> : <Sparkles size={17} />}{loading ? "Agent is reasoning..." : "Generate live brief"}</button>{error && <small className="agentError">{error}</small>}</div><AnimatePresence mode="wait">{brief && <motion.div className="agentResult" key={brief.headline} initial={{ opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0 }}><div className="agentMeta">{brief.provider} · {brief.model}</div>{brief.priorities.map((item, index) => <motion.article key={item.action} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .1 }}><b>0{index + 1}</b><div><strong>{item.action}</strong><p>{item.reason}</p><small>{item.owner} · {item.deadline}</small></div></motion.article>)}<p className="agentWatch"><strong>Watch:</strong> {brief.watch}</p></motion.div>}</AnimatePresence></section>;
}